name: Coveralls.io

on:
  workflow_dispatch:

jobs:
  coverage:
    name: Coverage report to Coveralls.io
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    
    - run: npm ci
    
    - run: npm run build --if-present

    - run: npm run coverage
      env:
        RPC_PROVIDER_URL: ${{ secrets.RPC_PROVIDER_URL }}
        ETHERS_WALLET_ADDRESS: ${{ secrets.ETHERS_WALLET_ADDRESS }}
        ETHERS_WALLET_PRIVATE_KEY: ${{ secrets.ETHERS_WALLET_PRIVATE_KEY }}

    - name: send report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
